### ISSUE TITLE
Entering same token

### ISSUE THREAD

**Issue by plpento** [EnAccess/OpenPAYGO-HW#3]
Hi,

Thanks for the work you have done for the implementation on Arduino.
I have an issue when I enter the same token, the device recognize it as valid and activate it again.
I have used the same key and starting code as the example.

(Token entered: 123456789)
(Activation Value from Token: -1)
(Count: 1)

(Token entered: 662486790)
(Activation Value from Token: 1)
(Count: 2)

Green LED Blinked 2 times!

(Token entered: 662486790)
(Activation Value from Token: 1)
(Count: 2)

Green LED Blinked 2 times!

Thanks,

plpento

**Comment by benmod** [comment]
Hi Panos, 

Thanks a lot for reporting this issue! 

It seems that it was introduced in the latest update to the examples and this is now fixed in v2.1.2. 

Let me know if I can help you further. 

Cheers!
Ben
